"""Pages module"""

from . import (
    page_01_hall_overview,
    page_02_daily_analysis,
    page_03_weekday_analysis,
    page_04_dd_analysis,
    page_05_last_digit,
    page_06_day_last_digit,
    page_07_nth_weekday,
    page_08_individual_machines,
    page_09_machine_tail,
    page_10_period_top10,
    page_11_cross_search,
    page_12_statistics,
    page_13_hall_selection,
    page_14_notion_exporter,
    page_15_backtest_validation,
    page_16_cross_search_bulk,
    page_17_heatmap,
    page_18_daily_report,
    page_19_daily_report_visual_test,
    page_20_kamata7_theory,
    page_21_kamata7_event_checks,
    page_22_kamata7_segments,
)

__all__ = [
    'page_01_hall_overview',
    'page_02_daily_analysis',
    'page_03_weekday_analysis',
    'page_04_dd_analysis',
    'page_05_last_digit',
    'page_06_day_last_digit',
    'page_07_nth_weekday',
    'page_08_individual_machines',
    'page_09_machine_tail',
    'page_10_period_top10',
    'page_11_cross_search',
    'page_12_statistics',
    'page_13_hall_selection',
    'page_14_notion_exporter',
    'page_15_backtest_validation',
    'page_16_cross_search_bulk',
    'page_17_heatmap',
    'page_18_daily_report',
    'page_19_daily_report_visual_test',
    'page_20_kamata7_theory',
    'page_21_kamata7_event_checks',
    'page_22_kamata7_segments',
]
