"""Pages module"""

from . import (
    page_01_hall_overview,
    page_02_single_axis_viewer,
    page_04_dd_analysis,
    page_08_individual_machines,
    page_10_period_top10,
    page_11b_interaction_explorer,
    page_11c_axis_screening,
    page_11_cross_search,
    page_12_statistics,
    page_13_hall_selection,
    page_14_notion_exporter,
    page_15_backtest_validation,
    page_16_cross_search_bulk,
    page_17_heatmap,
    page_18_daily_report,
    page_19_daily_report_visual_test,
    page_20_theory_verification,
)

__all__ = [
    'page_01_hall_overview',
    'page_02_single_axis_viewer',
    'page_04_dd_analysis',
    'page_08_individual_machines',
    'page_10_period_top10',
    'page_11b_interaction_explorer',
    'page_11c_axis_screening',
    'page_11_cross_search',
    'page_12_statistics',
    'page_13_hall_selection',
    'page_14_notion_exporter',
    'page_15_backtest_validation',
    'page_16_cross_search_bulk',
    'page_17_heatmap',
    'page_18_daily_report',
    'page_19_daily_report_visual_test',
    'page_20_theory_verification',
]
